version: "2"
volumes:
  resin-data:
services:
  shell:
    build: ./opensshd
    network_mode: "host"
    volumes:
      - "resin-data:/data"
    labels:
      io.balena.features.supervisor-api: "1"
  main:
    build: ./zoobc-core
    command: ['--env-override', '--debug']
    network_mode: "host"
    volumes:
      - "resin-data:/data"
    labels:
      io.balena.features.supervisor-api: "1"
  n2:
    # image: busybox:musl
    build: ./zoobc-core
    command: ['--env-override', '--debug']
    network_mode: "host"
    volumes:
      - "resin-data:/data"
    labels:
      io.balena.features.supervisor-api: "1"
  grpcweb:
    build: ./grpcwebproxy
    network_mode: "host"
    depends_on:
      - main
  sqliteweb:
    build: ./sqlite-web
    network_mode: "host"
    volumes:
      - "resin-data:/data"
    environment:
      - SQLITE_DATABASE=/data/zoobc-core/main/zoobc.db
      - SQLITE_WEB_PASSWORD=login123
